{% set version = '2.1' %}

package:
  name: pblat
  version: {{ version }}

source:
  url: https://github.com/icebert/pblat/archive/{{ version }}.tar.gz
  sha256: fb4651d6543cecc887044bfccffcaff4afcbb6f4a3cf2da6004f646a2459c781

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - openssl
    - zlib
  run:

test:
  commands:
    - 'pblat 2>&1 | grep "^usage:"'

about:
  home: https://github.com/icebert/pblat
  license: Free for academic, nonprofit and personal use
  summary: parallelized blat with multi-threads support
  
